export const GET_ALL = 'GET_ALL'
export const GET_BY_NAME = 'GET_BY_NAME'
export const CLEAR_FILTER = 'CLEAR_FILTER'
export const NOT_FOUND = 'NOT_FOUND'
export const GET_TEMPS = 'GET_TEMPS'
export const FILTER_TEMPS = 'FILTER_TEMPS'
export const ORDER = 'ORDER'
export const ORIGIN = 'ORIGIN'
